start: sum_reverse_sort.cpp sum_reverse_sort.h
	g++ -c -Wall -Wextra -pedantic sum_reverse_sort.cpp
	g++ -c -Wall -Wextra -pedantic main.cpp
	g++ main.o sum_reverse_sort.o -o output
clean:
	rm main.o && rm sum_reverse_sort.o